import { useState } from "react";
import Button from "../../components/Button";
import ClearButton from "../../components/ClearButton";
import ErrorMessage from "../../components/ErrorMessage";
import ExampleSelector from "../../components/ExampleSelector";
import InputEditor from "../../components/InputEditor";
import OutputArea from "../../components/OutputArea";
import Seo from "../../components/Seo";
import ToolLayout from "../../components/ToolLayout";
import { TOOLS } from "../../data/toolRegistry";
import {
  formatObjectIdSummary,
  generateObjectId,
  parseObjectId,
  type ObjectIdInfo,
} from "../../tools/objectid/objectId";

const EXAMPLES = [
  { name: "Classic ObjectId", value: "507f1f77bcf86cd799439011" },
  { name: "Epoch (1970)", value: "000000000000000000000000" },
  { name: "Max timestamp", value: "ffffffffffffffffffffffff" },
  { name: "Modern ObjectId", value: "6618e8b4f2a9c3d1e4b7a1c2" },
];

export default function ObjectIdTimestampPage() {
  const [input, setInput] = useState("");
  const [result, setResult] = useState<ObjectIdInfo | null>(null);
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");

  const run = (raw: string) => {
    if (raw.trim() === "") {
      setError("Enter a 24-character ObjectId to convert.");
      setResult(null);
      setOutput("");
      return;
    }
    try {
      const info = parseObjectId(raw);
      setResult(info);
      setOutput(formatObjectIdSummary(info));
      setError("");
    } catch (err) {
      setResult(null);
      setOutput("");
      setError(err instanceof Error ? err.message : "Invalid ObjectId.");
    }
  };

  const handleGenerate = () => {
    const hex = generateObjectId();
    setInput(hex);
    run(hex);
  };

  const handleClear = () => {
    setInput("");
    setResult(null);
    setOutput("");
    setError("");
  };

  const related = TOOLS.filter((tool) =>
    ["mongodb-uri-parser", "mongodb-query-formatter", "mongodb-aggregation-formatter"].includes(
      tool.slug
    )
  );

  return (
    <ToolLayout
      title="MongoDB ObjectId to Timestamp"
      description="Convert a MongoDB ObjectId into its creation timestamp and see the date in UTC and in your local time. Also generate new ObjectIds."
      howItWorks={[
        {
          title: "Timestamp embedded in the ObjectId",
          body: "An ObjectId is a 12-byte value shown as 24 hexadecimal characters. The first 4 bytes are the creation time as Unix seconds. This tool reads those bytes and converts them into a human-readable date — no database connection required.",
        },
        {
          title: "Validation",
          body: "Input is checked for the exact 24-character hexadecimal format before parsing, so invalid values produce a clear error instead of a wrong date.",
        },
        {
          title: "Generation",
          body: "The Generate button builds a new ObjectId with the current timestamp plus a cryptographically random suffix, following the same layout the MongoDB drivers use.",
        },
      ]}
      commonUses={[
        "Finding out when a document was created from its _id.",
        "Debugging data imported from another system.",
        "Sorting collections by creation time without a createdAt field.",
        "Generating test ObjectIds for fixtures and seed data.",
      ]}
      faqs={[
        {
          question: "Is the ObjectId timestamp exact?",
          answer:
            "It has one-second precision, so it tells you the second the ObjectId was created, not the exact millisecond.",
        },
        {
          question: "Why is the local date different from the UTC date?",
          answer:
            "UTC is the absolute time. The local date is the same instant shown in your computer's timezone.",
        },
        {
          question: "Does this work for every ObjectId?",
          answer:
            "Yes, for all 24-character ObjectIds generated by MongoDB drivers or tools. Values from other systems may not follow the timestamp layout.",
        },
        {
          question: "Is my ObjectId sent to a server?",
          answer:
            "No. Parsing and generation happen entirely in your browser.",
        },
      ]}
      relatedTools={related}
    >
      <Seo
        title="MongoDB ObjectId to Timestamp Converter — Free Tool"
        description="Convert a MongoDB ObjectId to its creation timestamp and date (UTC and local). Validate and generate ObjectIds — 100% client-side."
        path="/tools/mongodb-objectid-timestamp/"
        jsonLd={{
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "MongoDB ObjectId to Timestamp Converter",
          description:
            "Convert a MongoDB ObjectId into its creation timestamp. Runs locally in the browser.",
          applicationCategory: "DeveloperApplication",
          operatingSystem: "Any",
          browserRequirements: "Requires JavaScript",
          offers: { "@type": "Offer", price: "0" },
        }}
      />

      <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
          <ExampleSelector label="Examples" examples={EXAMPLES} onSelect={(value) => run(value)} />
          <span className="text-xs text-slate-500">Input &amp; output stay in your browser</span>
        </div>
        <InputEditor
          label="ObjectId (24 hex characters)"
          value={input}
          onChange={setInput}
          onRun={() => run(input)}
          rows={2}
          placeholder="507f1f77bcf86cd799439011"
          autoFocus
        />
        <div className="mt-4 flex flex-wrap items-center gap-2">
          <Button onClick={() => run(input)}>Convert</Button>
          <Button variant="secondary" onClick={handleGenerate}>
            Generate ObjectId
          </Button>
          <ClearButton onClick={handleClear} disabled={input === "" && output === ""} />
        </div>
        {error !== "" && (
          <div className="mt-4">
            <ErrorMessage message={error} />
          </div>
        )}
      </div>

      <OutputArea
        label={result ? "Result" : "Output"}
        value={output}
        downloadName="objectid-timestamp.txt"
      />

      <section aria-label="Result details" className={result ? "" : "hidden"}>
        {result && (
          <dl className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2">
            <div>
              <dt className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
                Timestamp (Unix seconds)
              </dt>
              <dd className="mt-1 font-mono text-sm text-slate-900">{result.timestampSeconds}</dd>
            </div>
            <div>
              <dt className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
                UTC date
              </dt>
              <dd className="mt-1 font-mono text-sm text-slate-900">{result.utcIso}</dd>
            </div>
            <div>
              <dt className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
                Local date
              </dt>
              <dd className="mt-1 font-mono text-sm text-slate-900">{result.localString}</dd>
            </div>
            <div>
              <dt className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
                Machine / counter bytes
              </dt>
              <dd className="mt-1 font-mono text-sm text-slate-900">
                {result.machine} / {result.counter}
              </dd>
            </div>
          </dl>
        )}
      </section>
    </ToolLayout>
  );
}
